knp_paginator:
    page_range: 5                      # nombre de pages dans la barre de navigation
    default_options:
        page_name: page                # nom du paramètre dans l'URL
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
