symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600 # Durée de validité du token en secondes (ici, 1 heure)
    throttle_limit: 3600 # Limite de fréquence des demandes