security:
    # Encodage / hash des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d'utilisateurs (depuis la base de données)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Développement : pas de sécurité pour les assets et le profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Pare-feu principal
        main:
            lazy: true
            provider: app_user_provider

            # Connexion par formulaire
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                username_parameter: _username
                password_parameter: _password

            # Déconnexion
            logout:
                path: app_logout
                target: app_login

            # Optionnel : se souvenir de moi (cookie de session persistant)
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine en secondes
                path: /

    # Accès selon les rôles
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
