parameters:
    locale: 'fr'
    attachments_directory: '%kernel.project_dir%/public/uploads/attachments'
    profiles_directory: '%kernel.project_dir%/public/uploads/profiles'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Form\PostType:
        arguments:
            $security: '@Symfony\Bundle\SecurityBundle\Security'

    App\EventListener\NotificationSubscriber:
        arguments:
            $security: '@Symfony\Bundle\SecurityBundle\Security'
        tags:
            - { name: kernel.event_subscriber }
